/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */

import java.io.IOException;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.MultipartConfig;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.Part;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author LENOVO
 */
@WebServlet(urlPatterns = {"/productForm"})

@MultipartConfig(
//    location = "/tmp/uploads",  // Temporary file storage location
    maxFileSize = 10485760,     // 10MB max file size
    maxRequestSize = 20971520,  // 20MB max request size
    fileSizeThreshold = 1024    // 1KB threshold before writing to disk
)

public class productFormServlet extends HttpServlet {

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        
          int userId = Integer.parseInt(request.getParameter("id"));
                   
          String name = request.getParameter("name");
          String category = request.getParameter("category");
          double price = Double.parseDouble(request.getParameter("price"));
          int total_stock = Integer.parseInt(request.getParameter("total_stock"));
          String description = request.getParameter("description");
          
          Part imagePart = request.getPart("image");
          InputStream imageInput = imagePart.getInputStream();
          String imageName = imagePart.getSubmittedFileName();
          String mimeType = imagePart.getContentType();
          
          
                
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
                            
              String sqlForProducts = "INSERT INTO products (name, category, price, total_stock, description, seller_id) values (?,?,?,?,?,?)";
              String sqlForImages = "INSERT into images(product_id, image_name, image_type, image_data) values (?, ?, ?, ?)";
             
                         
                try(
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/plantdb","root", "Shiv26@333");    
                    PreparedStatement psForProducts = conn.prepareStatement(sqlForProducts, Statement.RETURN_GENERATED_KEYS);
                ){
                    psForProducts.setString(1,name);
                    psForProducts.setString(2,category);
                    psForProducts.setDouble(3,price);
                    psForProducts.setInt(4,total_stock);
                    psForProducts.setString(5,description);
                    psForProducts.setInt(6,userId);
                     
                    int result = psForProducts.executeUpdate();
                    
                    int autoGeneratedKey = 0;
                    
                    if (result > 0) {
                        ResultSet rs = psForProducts.getGeneratedKeys();    
                        if(rs.next()){
                            autoGeneratedKey = rs.getInt(1);
                        }
                    }
                    
                    
                    try(
                            PreparedStatement psForImages = conn.prepareStatement(sqlForImages);
                    ){
                           psForImages.setInt(1,autoGeneratedKey);
                           psForImages.setString(2, imageName);
                           psForImages.setString(3,mimeType);
                           psForImages.setBlob(4,imageInput);

                            
                    int result1 = psForImages.executeUpdate();
          
                    if(result1>0){
                        System.out.println("image inserted successfully");
                    }else{
                        System.out.println("image couldn't be inserted");
                       
                    }
                    }
                }    
                    
                 
                response.sendRedirect("productForm.jsp");
                
//                    ps.close();
//                    conn.close();
           
              
          
          }catch(Exception e){
              e.printStackTrace();
              response.sendRedirect("registration.jsp?error=exception");
          }
          
    }

    

}
